stages:
  
  prepare:
    
    cmd: cd notebooks && papermill prep.ipynb ..\ex_notebooks\prep.ipynb
    
    deps:
      - safety-helmet-1/data.yaml
      - notebooks\prep.ipynb
    
    outs:
      - ex_notebooks\prep.ipynb

  
  train:
    
    cmd: cd notebooks && papermill train.ipynb ..\ex_notebooks\train.ipynb
    
    deps:
      - safety-helmet-1/data.yaml
      - notebooks\train.ipynb
      - params.yaml
      - yolo11n.pt

    outs:
      - runs
      - mlflow
      - ex_notebooks\train.ipynb